# Generated by Django 4.2.6 on 2023-10-28 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100, verbose_name='Тест')),
                ('title', models.CharField(max_length=127, verbose_name='Название теста')),
                ('correct', models.PositiveIntegerField(verbose_name='Правильных ответов')),
                ('total', models.PositiveIntegerField(verbose_name='Всего вопросов')),
                ('done', models.DateTimeField(verbose_name='Сделано в:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История теста',
                'verbose_name_plural': 'История тестов',
            },
        ),
    ]
