# Generated by Django 4.2.6 on 2023-10-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_testlog_correct_alter_testlog_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlog',
            name='done',
            field=models.DateTimeField(verbose_name='Сделано в:'),
        ),
    ]
