# Generated by Django 4.2.6 on 2023-10-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_testlog_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlog',
            name='title',
            field=models.CharField(default='title', max_length=127, verbose_name='Название теста'),
            preserve_default=False,
        ),
    ]
