# Generated by Django 4.2.6 on 2023-10-27 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
    ]
