# Generated by Django 4.2.6 on 2023-10-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_code',
            field=models.CharField(default='', max_length=5, verbose_name='Код восстановления'),
        ),
    ]
